### ISSUE TITLE
Question: Has non-JS based DataBinding worked?

### ISSUE THREAD

**Issue by wridgeu** [mauriciolauffer/openui5-model-odata-v2-odatamodelpromise#7]
Hi Mauricio,

setting UI5 2.0, OData V4 and every goodie in the past few months/years aside. I was wondering if using `openui5.model.odata.v2.ODataModelPromise` as type within the `manifest.json` has ever worked for you? 

I'm asking because back when you initially made this repository public, I tried it out and it didn't work (iirc). I thought since you still actively maintain it, it wouldn't hurt asking. In your example application it doesn't seem to work either. 

![image](https://github.com/mauriciolauffer/openui5-model-odata-v2-odatamodelpromise/assets/14982812/2bcfc3b7-3d3d-4d08-a13a-dd3e3328cefb)

The data is there, it is in the model and the requests are triggered based on the binding in the view. However, not shown/not displayed in the end.
![image](https://github.com/mauriciolauffer/openui5-model-odata-v2-odatamodelpromise/assets/14982812/de3b4a92-6191-4cb8-896b-c82092b3dc20)

My assumption at first was that the binding is created, the requests made and as soon as the model retrieved the data, the binding should recognize the change (or rather the model should inform the binding) in the model and refresh/update the control based on that. Am I missing something or do I maybe have the wrong mental model here?

Thanks in advance,
Marco :)

**Comment by LipinArts** [comment]
> Hi Mauricio,
> 
> setting UI5 2.0, OData V4 and every goodie in the past few months/years aside. I was wondering if using `openui5.model.odata.v2.ODataModelPromise` as type within the `manifest.json` has ever worked for you?
> 
> I'm asking because back when you initially made this repository public, I tried it out and it didn't work (iirc). I thought since you still actively maintain it, it wouldn't hurt asking. In your example application it doesn't seem to work either.
> 
> ![image](https://private-user-images.githubusercontent.com/14982812/296837717-2bcfc3b7-3d3d-4d08-a13a-dd3e3328cefb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNjE4ODUsIm5iZiI6MTcyMzM2MTU4NSwicGF0aCI6Ii8xNDk4MjgxMi8yOTY4Mzc3MTctMmJjZmMzYjctM2QzZC00ZDA4LWExM2EtZGQzZTMzMjhjZWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA3MzMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YzgxOGJlMmI1Y2ZhYjY3Y2UyMDI1NjIwMDY0NjAwZGYzNjAwMmI1YWM3ZWIxZjIzNDA3OTIzYjE1OWU4MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u7Hnc4J3GiqPEx3Hd6uxSLvN0rZxOI0RsY1EtrurCm8)
> 
> The data is there, it is in the model and the requests are triggered based on the binding in the view. However, not shown/not displayed in the end. ![image](https://private-user-images.githubusercontent.com/14982812/296841585-de3b4a92-6191-4cb8-896b-c82092b3dc20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNjE4ODUsIm5iZiI6MTcyMzM2MTU4NSwicGF0aCI6Ii8xNDk4MjgxMi8yOTY4NDE1ODUtZGUzYjRhOTItNjE5MS00Y2I4LTg5NmItYzgyMDkyYjNkYzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA3MzMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5OTdlMzkxMzJlNjM5NzBiODM3ZTNiNDNjMTc1N2ZlNzA4YTBkM2JhMjQ5MThkOTkwMzc5ZjFkN2MwZTY1MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ocmxKrGeQTzeoRCKTdnTU3Q-qkNbUU3ZvMzX1HxxdM4)
> 
> My assumption at first was that the binding is created, the requests made and as soon as the model retrieved the data, the binding should recognize the change (or rather the model should inform the binding) in the model and refresh/update the control based on that. Am I missing something or do I maybe have the wrong mental model here?
> 
> Thanks in advance, Marco :)

In the case of binding, such a model will not work because it expects a callback under the hood, whereas the current model returns a promise (yes, the same methods `create`, `read`, `update`, `delete` are called during binding). To fix this, you need to rename the implemented methods with promises so that they differ from the native ones. For example, use `readAsync` and call them, leaving the native methods as they are. This way, both binding will work and you can manually use the methods with promises.
<img width="761" alt="image" src="https://github.com/user-attachments/assets/86c6f133-04c2-4278-b37d-fcc1d7ca3e1b">

**Comment by wridgeu** [comment]
Hey @LipinArts, I didn't even remember asking this here haha - yeah, you're totally right. 

Making the model effectively a side-by-side usage by letting UI5 itself access the core methods like it is used to and using the async ones yourself is probably the best way to go.

Appreciate your input! :)
